# Generated by Django 4.0.5 on 2023-08-31 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='tags',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[['Fiat', 'Fiat'], ['Chevrolet', 'Chevrolet'], ['Ford', 'Ford'], ['Toyota', 'Toyota']], default='Ford', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
