# Generated by Django 4.0.5 on 2023-09-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_rename_tags_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[['Ford', 'Ford'], ['Chevrolet', 'Chevrolet'], ['Fiat', 'Fiat'], ['Toyota', 'Toyota']], default='Ford', max_length=20),
        ),
    ]
