# Generated by Django 4.0.5 on 2023-09-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_fecha_creacion_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerListadoPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('visualizar_catalogo', 'Puede ver el listado de vehículos')],
            },
        ),
    ]
