# Generated by Django 4.0.5 on 2023-09-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_verlistadopermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerListadoPermission',
        ),
    ]
