# Generated by Django 4.0.5 on 2023-09-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_delete_verlistadopermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Puede visualizar listado'), ('add_vehiculomodel', 'Puede agregar vehículos'))},
        ),
    ]
